receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 1s
          metrics_path: /q/metrics
          static_configs:
            - targets:
                - observability-app:8080

  filelog:
    include:
      - /var/log/observability-app/*.log
    multiline:
      line_start_pattern: ^Exception

exporters:
  otlp:
    endpoint: tempo:4319
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
  prometheusremotewrite:
    endpoint: http://mimir:9009/api/v1/push
  debug:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: true
      job: true
      instance: true
      level: true
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [debug, prometheus, prometheusremotewrite]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [debug, loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]