global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1s
    static_configs:
      - targets:
          - otel-collector-contrib:8889
          - otel-collector-contrib:8888
  # Prometheus will scrape the exporter on the “metrics_path”, and the exporter will then scrape the "static_configs.targets".
  # "metrics_path", is here the PATH on which the exporter exposes metrics 
  - job_name: blackbox-exporter
    # scheme: http
    metrics_path: /probe # Default is /metrics, But since it's an exporter, we put the PATH of the exporter
    params:
      module: [ http_2xx ]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - http://observability-app:8080/q/health    # Target that the exporter will check 
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.