global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets:
          - vector-default-conf:9598