apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    editable: false
    jsonData:
      derivedFields:
        - name: 'trace_id'
          matcherRegex: '"traceid":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: 'tempo'

  - name: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        mappedTags: [ { key: 'service.name', value: 'job' } ]
        mapTagNamesEnabled: true
        filterByTraceID: true
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki

  - name: Mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    editable: false
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo