apiVersion: 1

datasources:

  - name: Prometheus
    uid: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: Tempo

  - name: Loki
    uid: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    editable: false
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: "traceId:(\\w+)"
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'
          datasourceUid: Tempo
          # optional for URL Label to set a custom display label for the link.
          urlDisplayLabel: View Trace

  - name: Tempo
    uid: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        mappedTags: [ { key: 'service.name', value: 'job' } ]
        mapTagNamesEnabled: true
        filterByTraceID: true
      serviceMap:
        datasourceUid: Prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: Loki

  - name: Mimir
    uid: Mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    editable: false
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: Tempo

  - name: Pyroscope
    uid: Pyroscope
    type: grafana-pyroscope-datasource
    url: http://pyroscope:4040
    jsonData:
      minStep: 15s